export const apiStrategies = [
  {
    id: "alpha-pulse",
    name: "Alpha Pulse",
    manager: "NorthBridge Quant",
    category: "Momentum",
    status: "Verified",
    risk: "Medium",
    monthlyReturn: 8.4,
    drawdown: 6.2,
    sharpe: 2.18,
    winRate: 63,
    trades: 418,
    markets: ["BTC", "ETH", "NASDAQ"],
  },
  {
    id: "delta-grid",
    name: "Delta Grid",
    manager: "Aster Capital Systems",
    category: "Mean Reversion",
    status: "Live",
    risk: "Low",
    monthlyReturn: 4.7,
    drawdown: 3.1,
    sharpe: 1.76,
    winRate: 71,
    trades: 1260,
    markets: ["EURUSD", "GBPUSD", "Gold"],
  },
  {
    id: "breakline-x",
    name: "Breakline X",
    manager: "Vektor Labs",
    category: "Breakout",
    status: "Verified",
    risk: "High",
    monthlyReturn: 13.9,
    drawdown: 11.8,
    sharpe: 1.92,
    winRate: 52,
    trades: 286,
    markets: ["NASDAQ", "S&P 500", "BTC"],
  },
];

export const apiPortfolio = {
  accountId: "demo-investor-001",
  capitalAllocated: 500000,
  openPnl: 42200,
  weightedMonthlyReturn: 8.4,
  maxDrawdown: 9.6,
  riskMode: "Normal",
  allocations: [
    {
      strategyId: "alpha-pulse",
      name: "Alpha Pulse",
      capital: 250000,
      pnl: 21250,
      exposure: 72,
      status: "Running",
    },
    {
      strategyId: "delta-grid",
      name: "Delta Grid",
      capital: 150000,
      pnl: 7050,
      exposure: 44,
      status: "Running",
    },
    {
      strategyId: "breakline-x",
      name: "Breakline X",
      capital: 100000,
      pnl: 13900,
      exposure: 61,
      status: "Reduced",
    },
  ],
};

export const apiSubmissions = [
  {
    id: "institutional-momentum-alpha",
    name: "Institutional Momentum Alpha",
    manager: "NorthBridge Quant",
    status: "Pending",
    documentation: "Complete",
    brokerEvidence: "Uploaded",
    maxDrawdown: 6.9,
    sharpe: 2.04,
  },
  {
    id: "fx-carry-grid",
    name: "FX Carry Grid",
    manager: "Aster Capital Systems",
    status: "Approved",
    documentation: "Complete",
    brokerEvidence: "Verified",
    maxDrawdown: 3.7,
    sharpe: 1.61,
  },
  {
    id: "micro-volatility-sniper",
    name: "Micro Volatility Sniper",
    manager: "Obsidian Execution",
    status: "Rejected",
    documentation: "Partial",
    brokerEvidence: "Missing",
    maxDrawdown: 19.2,
    sharpe: 1.22,
  },
];

export const apiSystemHealth = {
  environment: "demo",
  apiVersion: "0.1.0",
  status: "operational",
  services: [
    {
      name: "Strategy API",
      status: "online",
      route: "/api/strategies",
    },
    {
      name: "Portfolio API",
      status: "online",
      route: "/api/portfolio",
    },
    {
      name: "Admin Submissions API",
      status: "online",
      route: "/api/admin/submissions",
    },
    {
      name: "Broker Execution API",
      status: "mocked",
      route: "/execution",
    },
  ],
};